version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network

  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./.env:/app/.env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
